cc_library(
    name = "rate_limiter",
    srcs = ["RateLimiter.cc"],
    hdrs = ["RateLimiter.h"],
    deps = ["//src/cc/rpc/modules/interface:interface", "@com_github_grpc_grpc//:grpc++", "@com_google_protobuf//:protoc"],
    visibility = ["//visibility:public"],
)

