cc_library(
    name = "server",
    srcs = ["Server.cc"],
    hdrs = ["Server.h"],
    deps = [
        "//src/cc/rpc/modules/rate_limiter:rate_limiter",
        "//src/proto:service_cc_grpc",
    ],
    visibility = ["//visibility:public"],
)

